# Generated by Django 4.2.30 on 2026-08-02 22:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wallet', '0010_transaction_type_penalite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tontine', '0016_penalite_constraints'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('transaction_contestee', 'Transaction contestée'), ('cotisation_non_creditee', 'Cotisation non créditée'), ('litige_entre_membres', 'Litige entre membres'), ('autre', 'Autre')], max_length=32, verbose_name='Catégorie')),
                ('subject', models.CharField(help_text='Résumé court affiché en liste.', max_length=255, verbose_name='Objet')),
                ('description', models.TextField(help_text="Détail de la réclamation tel que rapporté par l'utilisateur.", verbose_name='Description')),
                ('status', models.CharField(choices=[('ouvert', 'Ouvert'), ('en_cours_examen', "En cours d'examen"), ('resolu', 'Résolu'), ('rejete', 'Rejeté')], default='ouvert', max_length=20, verbose_name='Statut')),
                ('opened_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ouverture")),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de résolution')),
                ('decision', models.TextField(blank=True, default='', help_text='Verdict rendu par le staff (résolu/rejeté) : obligatoire à la résolution.', verbose_name='Décision')),
                ('resolution_reason', models.TextField(blank=True, default='', help_text="Motif de la décision, dupliqué depuis le journal d'audit (AdminActionLog) pour rester lisible directement sur le litige.", verbose_name='Motif')),
                ('opened_by', models.ForeignKey(blank=True, help_text="Utilisateur (client final) à l'origine du litige. SET_NULL (et non CASCADE) : un litige doit survivre à la suppression du compte qui l'a ouvert, pour rester consultable dans l'historique.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disputes_opened', to=settings.AUTH_USER_MODEL, verbose_name='Ouvert par')),
                ('resolved_by', models.ForeignKey(blank=True, help_text='Membre du staff ayant tranché le litige — imputabilité de la décision.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disputes_resolved', to=settings.AUTH_USER_MODEL, verbose_name='Résolu par')),
                ('tontine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disputes', to='tontine.tontine', verbose_name='Tontine concernée')),
                ('transaction', models.ForeignKey(blank=True, help_text='SET_NULL : la transaction peut en théorie être purgée sans emporter la trace du litige qui la concernait.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disputes', to='wallet.transaction', verbose_name='Transaction contestée')),
            ],
            options={
                'verbose_name': 'Litige',
                'verbose_name_plural': 'Litiges',
                'ordering': ['opened_at'],
                'indexes': [models.Index(fields=['status', 'opened_at'], name='disputes_di_status_3cbd82_idx'), models.Index(fields=['category'], name='disputes_di_categor_03c929_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='dispute',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('resolved_at__isnull', True), ('resolved_by__isnull', True), ('status__in', ['ouvert', 'en_cours_examen'])), models.Q(('resolved_at__isnull', False), ('resolved_by__isnull', False), ('status__in', ['resolu', 'rejete'])), _connector='OR'), name='dispute_resolution_fields_consistent_with_status'),
        ),
        migrations.AddConstraint(
            model_name='dispute',
            constraint=models.CheckConstraint(check=models.Q(('resolved_at__isnull', True), ('resolved_at__gte', models.F('opened_at')), _connector='OR'), name='dispute_resolved_at_after_opened_at'),
        ),
        migrations.AddConstraint(
            model_name='dispute',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['ouvert', 'en_cours_examen']), models.Q(('decision', ''), _negated=True), _connector='OR'), name='dispute_resolved_requires_decision'),
        ),
    ]
