# Generated by Django 4.2.30 on 2026-07-24 12:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notifications',
            options={'ordering': ['-date_envoie']},
        ),
        migrations.AddField(
            model_name='notifications',
            name='category',
            field=models.CharField(choices=[('invitation', 'Invitation'), ('cotisation', 'Cotisation'), ('paiement', 'Paiement'), ('securite', 'Sécurité')], default='paiement', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notifications',
            name='date_lecture',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notifications',
            name='dedup_key',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='notifications',
            name='source_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notifications',
            name='source_type',
            field=models.CharField(blank=True, choices=[('tontine', 'Tontine'), ('cagnotte', 'Cagnotte'), ('solidarity', 'Solidarité'), ('wallet', 'Portefeuille'), ('transaction', 'Transaction'), ('invitation', 'Invitation'), ('auth', 'Authentification')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='contenu',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='date_envoie',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='expediteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications_envoyees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='notifications',
            index=models.Index(fields=['destinataire', 'est_lue'], name='notificatio_destina_309e9b_idx'),
        ),
        migrations.AddIndex(
            model_name='notifications',
            index=models.Index(fields=['destinataire', '-date_envoie'], name='notificatio_destina_f6c37c_idx'),
        ),
    ]
