# Generated by Django 4.2.30 on 2026-08-01 21:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0002_notification_fields_and_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=100, unique=True)),
                ('last_started_at', models.DateTimeField(blank=True, null=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('runs_ok', models.PositiveIntegerField(default=0)),
                ('runs_failed', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('push_enabled', models.BooleanField(default=True)),
                ('categories_muted', models.JSONField(blank=True, default=list)),
                ('quiet_hours_start', models.TimeField(blank=True, null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PushDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expo_token', models.CharField(max_length=255, unique=True)),
                ('device_id', models.CharField(blank=True, default='', max_length=128)),
                ('platform', models.CharField(choices=[('ios', 'iOS'), ('android', 'Android')], max_length=10)),
                ('app_version', models.CharField(blank=True, default='', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('failure_count', models.PositiveSmallIntegerField(default=0)),
                ('last_error', models.CharField(blank=True, default='', max_length=100)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PushOutbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('corps', models.CharField(max_length=500)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('statut', models.CharField(choices=[('QUEUED', 'En attente'), ('SENDING', "En cours d'envoi"), ('SENT', 'Envoyé'), ('FAILED', 'Échoué'), ('DROPPED', 'Abandonné')], default='QUEUED', max_length=10)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ticket_id', models.CharField(blank=True, default='', max_length=64)),
                ('receipt_checked_at', models.DateTimeField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='notifications',
            name='category',
            field=models.CharField(choices=[('invitation', 'Invitation'), ('cotisation', 'Cotisation'), ('paiement', 'Paiement'), ('securite', 'Sécurité'), ('epargne', 'Épargne'), ('gestion', 'Gestion du groupe')], max_length=20),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='source_type',
            field=models.CharField(blank=True, choices=[('tontine', 'Tontine'), ('cagnotte', 'Cagnotte'), ('solidarity', 'Solidarité'), ('wallet', 'Portefeuille'), ('transaction', 'Transaction'), ('invitation', 'Invitation'), ('auth', 'Authentification'), ('savings', 'Épargne personnelle')], default='', max_length=20),
        ),
        migrations.AddIndex(
            model_name='notifications',
            index=models.Index(fields=['date_envoie'], name='notificatio_date_en_e449a3_idx'),
        ),
        migrations.AddField(
            model_name='pushoutbox',
            name='destinataire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_outbox_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pushoutbox',
            name='notification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='push_outbox_entries', to='notifications.notifications'),
        ),
        migrations.AddField(
            model_name='pushdevice',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_devices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preference', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='pushoutbox',
            index=models.Index(fields=['statut', 'next_attempt_at'], name='notificatio_statut_2d19ec_idx'),
        ),
        migrations.AddIndex(
            model_name='pushoutbox',
            index=models.Index(fields=['statut', 'receipt_checked_at'], name='notificatio_statut_5c5de9_idx'),
        ),
        migrations.AddIndex(
            model_name='pushdevice',
            index=models.Index(fields=['user', 'is_active'], name='notificatio_user_id_fa4742_idx'),
        ),
        migrations.AddConstraint(
            model_name='pushdevice',
            constraint=models.UniqueConstraint(condition=models.Q(('device_id__gt', '')), fields=('user', 'device_id'), name='uniq_pushdevice_user_device_id'),
        ),
    ]
