from django.urls import path

from .views import (
    accept_invitation,
    annuler_penalite,
    attribute_penalite,
    changer_tour,
    cotiser_tontine,
    create_tontine,
    exclude_member,
    list_chat_messages,
    list_members,
    list_my_penalites,
    list_penalites,
    post_chat_message,
    define_tontine_regle,
    demarrer_tontine,
    get_tontine_detail,
    health,
    list_my_invitations,
    list_my_tontines_recruiting,
    list_tontines,
    modify_tontine_regle,
    preview_invitation,
    refuse_invitation,
    regler_penalite,
    send_invitation,
    set_member_role,
    set_ordre_ramassage,
    archive_groupe_tontine,
    delete_groupe_tontine,
)

urlpatterns = [
    path("health/", health, name="tontine-health"),
    path("", list_tontines, name="tontine-list"),
    path("recruiting/", list_my_tontines_recruiting, name="tontine-list-recruiting"),
    path("detail/", get_tontine_detail, name="tontine-detail"),
    path("create/", create_tontine, name="tontine-create"),
    path("regles/", define_tontine_regle, name="tontine-define-regles"),
    path("regles/modifier/", modify_tontine_regle, name="tontine-modify-regles"),
    path("invitations/", send_invitation, name="tontine-send-invitation"),
    path("invitations/mine/", list_my_invitations, name="tontine-my-invitations"),
    path("invitations/preview/", preview_invitation, name="tontine-preview-invitation"),
    path("invitations/accept/", accept_invitation, name="tontine-accept-invitation"),
    path("invitations/refuse/", refuse_invitation, name="tontine-refuse-invitation"),
    path("ordre/", set_ordre_ramassage, name="tontine-set-ordre"),
    path("cotiser/", cotiser_tontine, name="tontine-cotiser"),
    path("tours/demarrer/", demarrer_tontine, name="tontine-demarrer"),
    path("membres/", list_members, name="tontine-list-members"),
    path("membres/exclure/", exclude_member, name="tontine-exclude-member"),
    path("membres/role/", set_member_role, name="tontine-set-member-role"),
    path("penalites/attribuer/", attribute_penalite, name="tontine-attribute-penalite"),
    path("penalites/mine/", list_my_penalites, name="tontine-list-my-penalites"),
    path("penalites/", list_penalites, name="tontine-list-penalites"),
    path("penalites/regler/", regler_penalite, name="tontine-regler-penalite"),
    path("penalites/annuler/", annuler_penalite, name="tontine-annuler-penalite"),
    path("tours/changer/", changer_tour, name="tontine-changer-tour"),
    path("archive/", archive_groupe_tontine, name="tontine-archive"),
    path("delete/", delete_groupe_tontine, name="tontine-delete"),
    path("chat/", list_chat_messages, name="tontine-chat-list"),
    path("chat/send/", post_chat_message, name="tontine-chat-send"),
]
