# Generated by Django 4.2.30 on 2026-07-11 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_validation_versement_solidaire'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.UniqueConstraint(condition=models.Q(('statut_transaction', 'RÉUSSIE'), ('type_transaction', 'DÉBIT')), fields=('tour', 'wallet'), name='unique_debit_reussi_par_tour_et_wallet'),
        ),
    ]
