# Generated by Django 4.2.30 on 2026-07-11 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0006_transaction_unique_debit_reussi_par_tour_et_wallet'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='transaction',
            name='wallet_transaction_fk_coherence_type',
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('epargne__isnull', False), ('tontine__isnull', True), ('tour__isnull', True), ('type_transaction', 'VERSEMENT_EPARGNE_PERSONNELLE')), models.Q(('epargne__isnull', False), ('tontine__isnull', True), ('tour__isnull', True), ('type_transaction', 'RETRAIT_EPARGNE_PERSONNELLE')), models.Q(('epargne__isnull', True), ('tontine__isnull', True), ('tour__isnull', True), ('type_transaction', 'RETRAIT')), models.Q(('epargne__isnull', True), ('tontine__isnull', True), ('tour__isnull', True), ('type_transaction', 'DÉPÔT')), models.Q(('epargne__isnull', True), ('tontine__isnull', False), ('tour__isnull', False), ('type_transaction', 'DÉBIT')), models.Q(('epargne__isnull', True), ('tontine__isnull', False), ('tour__isnull', True), ('type_transaction', 'CONTRIBUTION_SOLIDAIRE')), models.Q(('epargne__isnull', True), ('tontine__isnull', False), ('tour__isnull', True), ('type_transaction', 'VERSEMENT_SOLIDAIRE')), models.Q(('epargne__isnull', True), ('tontine__isnull', False), ('tour__isnull', True), ('type_transaction', 'VALIDATION_VERSEMENT_SOLIDAIRE')), models.Q(('epargne__isnull', True), ('tontine__isnull', False), ('tour__isnull', True), ('type_transaction', 'CONTRIBUTION_CAGNOTTE')), models.Q(('epargne__isnull', True), ('tontine__isnull', False), ('tour__isnull', True), ('type_transaction', 'VERSEMENT_CAGNOTTE')), _connector='OR'), name='wallet_transaction_fk_coherence_type'),
        ),
    ]
