# Generated by Django 4.2.30 on 2026-07-24 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0007_remove_transaction_wallet_transaction_fk_coherence_type_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(check=models.Q(('montant_transaction__gt', 0)), name='transaction_montant_transaction_positif'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(check=models.Q(('solde_courant__gte', 0)), name='transaction_solde_courant_non_negatif'),
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.CheckConstraint(check=models.Q(('solde_courant__gte', 0)), name='wallet_solde_courant_non_negatif'),
        ),
    ]
