# Generated by Django 4.2.30 on 2026-05-02 22:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tontine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_tontine', models.CharField(choices=[('SOLIDAIRE', 'Tontine Solidaire'), ('GROUPE', 'Tontine de groupe'), ('CAGNOTTE', 'Cagnotte Association')], max_length=50)),
                ('est_active', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=300)),
                ('qr_code', models.CharField(max_length=500)),
                ('hote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TourTontine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_depose', models.DecimalField(decimal_places=0, max_digits=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('numero_du_tour', models.IntegerField()),
                ('tontine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tontine.tontine')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TontineRegle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectif_cotisation', models.DecimalField(decimal_places=0, max_digits=10)),
                ('montant_penalite', models.DecimalField(decimal_places=0, max_digits=10)),
                ('nombre_max', models.IntegerField()),
                ('ordre_aleatoire', models.BooleanField(default=False)),
                ('frequence', models.CharField(choices=[('HEBDOMADAIRE', 'Hebdomadaire'), ('JOURNALIER', 'Journalier'), ('MENSUEL', 'Mensuel'), ('PERSONNALISÉE', 'Personnalisée')], max_length=25)),
                ('frequence_personalise', models.IntegerField(blank=True, null=True)),
                ('tontine', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tontine.tontine')),
            ],
        ),
        migrations.CreateModel(
            name='TontineMembre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_membre', models.CharField(choices=[('ADMINISTRATEUR', 'Administrateur'), ('PARTICIPANT', 'Participant')], max_length=50)),
                ('statut_membre', models.CharField(choices=[('ACTIF', 'Actif'), ('EXCLU', 'Exclu'), ('A QUITTÉ', 'A quitté')], max_length=50)),
                ('date_adhesion', models.DateTimeField(auto_now_add=True)),
                ('ordre_ramassage', models.IntegerField()),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tontine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tontine.tontine')),
            ],
        ),
        migrations.AddField(
            model_name='tontine',
            name='membres',
            field=models.ManyToManyField(related_name='tontines_membres', through='tontine.TontineMembre', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Penalite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_penalite', models.DecimalField(decimal_places=0, max_digits=10)),
                ('montant_due', models.DecimalField(decimal_places=0, max_digits=10)),
                ('type_penalite', models.CharField(choices=[('RETARD PAIEMENT', 'Retard de paiement'), ('ABSENCE PAIEMENT', 'Absence de paiement')], max_length=25)),
                ('est_reglee', models.BooleanField(default=False)),
                ('date_attribution_penalite', models.DateTimeField(auto_now_add=True)),
                ('date_reglement_penalite', models.DateTimeField(blank=True, null=True)),
                ('tontine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tontine.tontine')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Invitations',
            fields=[
                ('numero_telephone_invite', models.CharField(max_length=15)),
                ('statut_invitation', models.CharField(choices=[('EN ATTENTE', 'En attente'), ('ACCEPTÉE', 'Acceptée')], default='EN ATTENTE', max_length=20)),
                ('est_utilisee', models.BooleanField(default=False)),
                ('date_invitation', models.DateTimeField(auto_now_add=True)),
                ('token', models.CharField(editable=False, help_text='Jeton opaque unique (clé de sécurité primaire).', max_length=64, primary_key=True, serialize=False)),
                ('tontine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tontine.tontine')),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('expediteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tontine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tontine.tontine')),
            ],
        ),
        migrations.AddConstraint(
            model_name='tourtontine',
            constraint=models.UniqueConstraint(fields=('tontine', 'numero_du_tour'), name='uniq_tontine_numero_tour'),
        ),
        migrations.AddConstraint(
            model_name='tontinemembre',
            constraint=models.UniqueConstraint(fields=('tontine', 'membre'), name='uniq_tontine_membre'),
        ),
        migrations.AddConstraint(
            model_name='tontinemembre',
            constraint=models.UniqueConstraint(fields=('tontine', 'ordre_ramassage'), name='uniq_tontine_ordre_ramassage'),
        ),
    ]
