# Generated by Django 4.2.30 on 2026-07-24 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cagnotte', '0003_rename_nom_cagnotte_cagnotte_numero_cagnotte'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cagnotte',
            constraint=models.CheckConstraint(check=models.Q(('objectif_cotisation__gt', 0)), name='cagnotte_objectif_cotisation_positif'),
        ),
    ]
