# Generated by Django 4.2.30 on 2026-05-06 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authn', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_inscription',
        ),
    ]
