# Generated by Django 4.2.30 on 2026-05-06 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authn', '0002_remove_user_date_inscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='code_pin',
            field=models.CharField(max_length=4),
        ),
    ]
