# Generated by Django 4.2.30 on 2026-05-06 23:22

import uuid
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("authn", "0003_alter_user_code_pin"),
    ]

    operations = [
        migrations.CreateModel(
            name="OtpChallenge",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("purpose", models.CharField(choices=[("login", "Login"), ("register", "Register"), ("reset_pin", "Reset PIN")], default="login", max_length=20)),
                ("code_hash", models.CharField(max_length=128)),
                ("expires_at", models.DateTimeField()),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("is_used", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="otp_challenges", to="authn.user")),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
    ]
