# Generated by Django 4.2.30 on 2026-05-08 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("authn", "0004_otpchallenge"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otpchallenge",
            name="user",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="otp_challenges", to="authn.user"),
        ),
        migrations.AddField(
            model_name="otpchallenge",
            name="pending_email",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
        migrations.AddField(
            model_name="otpchallenge",
            name="pending_first_name",
            field=models.CharField(blank=True, default="", max_length=150),
        ),
        migrations.AddField(
            model_name="otpchallenge",
            name="pending_last_name",
            field=models.CharField(blank=True, default="", max_length=150),
        ),
        migrations.AddField(
            model_name="otpchallenge",
            name="pending_phone",
            field=models.CharField(blank=True, default="", max_length=15),
        ),
        migrations.AddField(
            model_name="otpchallenge",
            name="pending_pin",
            field=models.CharField(blank=True, default="", max_length=4),
        ),
        migrations.AddField(
            model_name="otpchallenge",
            name="pending_username",
            field=models.CharField(blank=True, default="", max_length=150),
        ),
    ]
