# Generated by Django 4.2.30 on 2026-07-11 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authn', '0005_otpchallenge_pending_registration_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='code_pin',
            field=models.CharField(max_length=128),
        ),
    ]
