# Generated by Django 4.2.30 on 2026-07-24 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authn', '0007_hash_existing_code_pins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='numero_telephone',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
