"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

load_dotenv()

from apps import authn

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ["DJANGO_SECRET_KEY"]

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DJANGO_DEBUG", "False") == "True"

ALLOWED_HOSTS = [h.strip() for h in os.getenv("DJANGO_ALLOWED_HOSTS", "").split(",") if h.strip()]
if DEBUG and not ALLOWED_HOSTS:
    ALLOWED_HOSTS = ["localhost", "127.0.0.1"]


# Application definition

INSTALLED_APPS = [
    'corsheaders',
    'rest_framework',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'apps.authn',
    'apps.cagnotte',
    'apps.savings',
    'apps.tontine',
    'apps.solidarity',
    'apps.notifications',
    'apps.audits',
    'apps.wallet',
    'apps.kyc',
    'apps.disputes',
    'apps.administration',
    # Nécessaire pour révoquer les refresh tokens JWT existants (ex : après
    # une réinitialisation de PIN via apps.authn) — voir
    # apps/authn/views.py::_revoke_all_tokens_for_user.
    'rest_framework_simplejwt.token_blacklist',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # Doit rester le plus tôt possible : coupe court aux requêtes /api/admin/
    # hors allowlist IP avant toute résolution de session/CSRF.
    'apps.administration.middleware.AdminIpAllowlistMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # Nécessitent request.user (posé par AuthenticationMiddleware ci-dessus).
    'apps.administration.middleware.SessionFreshnessMiddleware',
    'apps.administration.middleware.AdminAuditTrailMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv("DB_NAME"),
        'USER': os.getenv("DB_USER"),
        'PASSWORD': os.getenv("DB_PASSWORD"),
        'HOST': os.getenv("DB_HOST"),
        'PORT': os.getenv("DB_PORT"),
        # Permet d'isoler la base de test via TEST_DB_NAME (utile quand
        # plusieurs suites tournent en parallèle : sans cela, elles partagent
        # toutes `test_<DB_NAME>` et se détruisent mutuellement la base en
        # cours d'exécution). Non défini => comportement Django par défaut.
        'TEST': {
            'NAME': os.getenv("TEST_DB_NAME") or None,
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Fichiers déposés par les utilisateurs (pièces KYC).
#
# MEDIA_URL n'est volontairement PAS défini et ce répertoire ne doit jamais
# être servi par le serveur web : les pièces d'identité ne sont lisibles que
# via `/api/admin/kyc/{id}/document/{type}/`, qui vérifie la permission et
# journalise chaque consultation. Exposer MEDIA_ROOT en statique reviendrait à
# publier les pièces d'identité des clients derrière une URL devinable.
MEDIA_ROOT = os.getenv("MEDIA_ROOT") or str(BASE_DIR / "private-media")

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CORS: wide open only in local dev (Expo/React Native clients use varying LAN origins).
# In production, set DJANGO_CORS_ALLOWED_ORIGINS to a comma-separated allowlist.
CORS_ALLOWED_ORIGINS = [o.strip() for o in os.getenv("DJANGO_CORS_ALLOWED_ORIGINS", "").split(",") if o.strip()]
CORS_ALLOW_ALL_ORIGINS = DEBUG and not CORS_ALLOWED_ORIGINS


AUTH_USER_MODEL = "authn.User"


# Mobile Money (Orange/MTN/Wave/Moov) sandbox flag.
#
# Il n'existe aujourd'hui AUCUNE intégration réelle avec un agrégateur Mobile
# Money : le endpoint wallet.deposit() crédite directement le wallet sans
# vérification externe. Tant que MOBILE_MONEY_SANDBOX=True, ce comportement
# est conservé (nécessaire au développement/démo) mais explicitement marqué
# comme "sandbox" dans la réponse JSON (cf. apps/wallet/views.py::deposit).
#
# Si un jour ce backend est déployé avec DEBUG=False sans avoir implémenté la
# véritable intégration Mobile Money, MOBILE_MONEY_SANDBOX doit être positionné
# à False (variable d'environnement) pour empêcher tout dépôt de créditer de
# l'argent fictif : le endpoint renverra alors 503 au lieu de créditer.
MOBILE_MONEY_SANDBOX = os.getenv("MOBILE_MONEY_SANDBOX", "True") == "True"


# CinetPay (agrégateur Mobile Money) — Checkout API v2.
#
# N'est utilisé que lorsque MOBILE_MONEY_SANDBOX=False (voir apps/wallet/views.py).
# CINETPAY_API_KEY/CINETPAY_SITE_ID sont les identifiants marchand CinetPay ;
# CINETPAY_NOTIFY_URL doit pointer vers le endpoint webhook public
# `wallet.cinetpay_notify` (POST, atteignable depuis Internet par les serveurs
# CinetPay) ; CINETPAY_RETURN_URL est l'URL/deeplink de retour affichée au
# client après paiement (page de statut côté app mobile).
CINETPAY_API_KEY = os.getenv("CINETPAY_API_KEY", "")
CINETPAY_SITE_ID = os.getenv("CINETPAY_SITE_ID", "")
CINETPAY_CURRENCY = os.getenv("CINETPAY_CURRENCY", "XOF")
CINETPAY_NOTIFY_URL = os.getenv("CINETPAY_NOTIFY_URL", "")
CINETPAY_RETURN_URL = os.getenv("CINETPAY_RETURN_URL", "")


# CinetPay Transfer/PayOut API v1 — utilisée uniquement pour le RETRAIT
# (apps/wallet/views.py::withdrawal, quand MOBILE_MONEY_SANDBOX=False).
#
# API distincte de la Checkout API ci-dessus (host, authentification et
# solde marchand différents) : CINETPAY_TRANSFER_PASSWORD est le mot de passe
# de transfert (distinct de CINETPAY_API_KEY/SITE_ID) fourni par CinetPay ;
# CINETPAY_TRANSFER_NOTIFY_URL doit pointer vers le endpoint webhook public
# `wallet.cinetpay_transfer_notify` (POST, atteignable depuis Internet) ;
# CINETPAY_DEFAULT_PHONE_PREFIX est l'indicatif pays (ex "225") utilisé pour
# séparer l'indicatif du numéro local quand `numero_telephone` ne le contient
# pas déjà.
CINETPAY_TRANSFER_PASSWORD = os.getenv("CINETPAY_TRANSFER_PASSWORD", "")
CINETPAY_TRANSFER_NOTIFY_URL = os.getenv("CINETPAY_TRANSFER_NOTIFY_URL", "")
CINETPAY_DEFAULT_PHONE_PREFIX = os.getenv("CINETPAY_DEFAULT_PHONE_PREFIX", "225")


# Envoi de SMS pour les OTP (apps/authn/sms.py).
#
# SMS_PROVIDER doit valoir "console" (dev — le code OTP est loggé en clair,
# jamais utiliser en production) ou "cinetpay" (envoi réel). Toute autre
# valeur fait échouer bruyamment l'envoi (SmsError), sans jamais dégrader
# silencieusement vers "console".
#
# CINETPAY_SMS_API_KEY/CINETPAY_SMS_SENDER concernent le compte SMS CinetPay
# (API Notitia), qui est SÉPARÉ du compte marchand Mobile Money utilisé pour
# les dépôts/retraits (CINETPAY_API_KEY plus haut) : ce compte SMS s'obtient
# auprès de hello@cinetpay.com, avec sa propre clé API et son propre sender
# ID alphanumérique (ex "COTICI").
SMS_PROVIDER = os.getenv("SMS_PROVIDER", "console")
CINETPAY_SMS_API_KEY = os.getenv("CINETPAY_SMS_API_KEY", "")
CINETPAY_SMS_SENDER = os.getenv("CINETPAY_SMS_SENDER", "")


# Push Expo (apps/notifications/push/expo.py). Optionnel : un projet Expo géré
# via EAS n'a pas forcément besoin d'un access token dédié pour l'envoi de
# push (seulement pour des quotas plus élevés / la gestion de plusieurs
# projets) — laissé vide, `expo.py` n'ajoute alors pas d'en-tête Authorization.
EXPO_ACCESS_TOKEN = os.getenv("EXPO_ACCESS_TOKEN", "")


# Pénalités de retard automatiques (apps/tontine/penalties.py,
# apps/tontine/management/commands/apply_tontine_penalties.py).
#
# Garde-fou CRITIQUE : sans lui, le premier passage du job de recouvrement
# après activation d'une règle historique (`TontineRegle.penalites_automatiques
# = True`) débiterait rétroactivement tous les tours déjà en retard depuis
# toujours. `PENALITES_AUTO_CUTOFF` doit être une date/heure ISO 8601
# (ex "2026-09-01T00:00:00Z") lue depuis l'environnement : aucun tour dont
# `date_echeance < cutoff` n'est jamais pénalisable, quelle que soit la règle
# de la tontine. Laissé vide (None), la fonctionnalité est désactivée
# GLOBALEMENT — c'est la valeur par défaut, à définir explicitement avant
# toute mise en production de cette fonctionnalité.
_penalites_auto_cutoff_raw = os.getenv("PENALITES_AUTO_CUTOFF", "")
if _penalites_auto_cutoff_raw:
    from django.utils.dateparse import parse_datetime as _parse_datetime_cutoff

    PENALITES_AUTO_CUTOFF = _parse_datetime_cutoff(_penalites_auto_cutoff_raw)
    if PENALITES_AUTO_CUTOFF is None:
        raise ValueError(
            "PENALITES_AUTO_CUTOFF doit être une date/heure ISO 8601 valide "
            f"(reçu : {_penalites_auto_cutoff_raw!r})."
        )
else:
    PENALITES_AUTO_CUTOFF = None


# Fuseau horaire "métier" des tontines (échéances, clôtures "23h59", alertes)
# — DISTINCT de `TIME_ZONE` (toujours "UTC", stockage). Abidjan n'observe pas
# de changement d'heure (UTC+0 toute l'année) : les deux sont aujourd'hui
# numériquement identiques, mais cette variable existe pour que le calcul de
# "23h59 heure locale" (apps/tontine/scheduling.py::cloture_cutoff) reste
# correct si COTICI ouvrait un jour à des utilisateurs dans un autre fuseau.
TONTINE_TIMEZONE = os.getenv("TONTINE_TIMEZONE", "Africa/Abidjan")


# Celery — clôture automatique des tours de tontine à échéance, alertes et
# relances de cotisation, recouvrement des dettes/pénalités (voir
# config/celery.py, apps/tontine/tasks.py, DEPLOYMENT.md).
#
# `CELERY_BROKER_URL`/`CELERY_RESULT_BACKEND` pointent par défaut vers un
# Redis local (dev) — à surcharger en production (ex : Redis managé). Aucune
# tâche ne dépend du résultat renvoyé (fire-and-forget, l'état applicatif
# vit en base via `TourTontine`/`Penalite`/`DetteCotisation`/`JobRun`), mais un
# backend est configuré pour permettre `task.get()` en tests/diagnostics.
CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL", "redis://localhost:6379/0")
CELERY_RESULT_BACKEND = os.getenv("CELERY_RESULT_BACKEND", "redis://localhost:6379/1")
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TIMEZONE = TONTINE_TIMEZONE
CELERY_ENABLE_UTC = True
# Une tâche qui plante ne doit jamais rester "en cours" indéfiniment côté
# worker (fuite de verrou applicatif `job_lock`, qui lui se relâche à la
# fermeture de connexion — mais mieux vaut un délai dur en secours) : borne
# stricte à 10 minutes, largement suffisante pour un lot de clôtures/15 min.
CELERY_TASK_TIME_LIMIT = 600
CELERY_TASK_SOFT_TIME_LIMIT = 540
# Acquitte la tâche APRÈS exécution (et non à sa réception) : un crash worker
# en cours de traitement doit pouvoir être rejoué par un autre worker plutôt
# que de perdre silencieusement le lot — sûr ici car chaque tâche est conçue
# pour être idempotente (job_lock + re-vérification sous verrou DB).
CELERY_TASK_ACKS_LATE = True


# Destination financière des pénalités de retard — point d'extension UNIQUE,
# voir apps/tontine/services/penalite_destination.py. En cours d'arbitrage
# métier : NE PAS changer cette valeur sans validation explicite de
# l'analyste métier ("beneficiaire_tour" = comportement historique, seul
# implémenté à ce jour).
PENALITE_DESTINATION_STRATEGY = os.getenv("PENALITE_DESTINATION_STRATEGY", "beneficiaire_tour")


REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 20,
    "DEFAULT_THROTTLE_RATES": {
        # Brute-force / SMS-bombing protection on OTP endpoints (PIN keyspace is only 4 digits).
        "otp_request": "5/hour",
        "otp_verify": "20/hour",
        # Bucket additionnel, keyé sur le numéro CIBLE (et non l'IP appelante) —
        # voir apps.authn.views.PhoneRateThrottle. Empêche le SMS-bombing d'un
        # même numéro depuis plusieurs IP différentes.
        "otp_request_phone": "5/hour",
        # Separate scope/bucket from otp_request: login attempts and OTP requests are
        # different concerns and must not share (or drain) the same rate-limit bucket.
        "login_attempt": "10/hour",
        # Réinitialisation de PIN (endpoint /reset-pin/) : action sensible,
        # jeton à courte durée de vie — scope dédié, séparé de otp_verify.
        "pin_reset": "10/hour",
        # Back-office administrateur (apps.administration) : scopes dédiés,
        # totalement séparés des scopes mobiles ci-dessus.
        "admin_login": "10/hour",
        "admin_action": "120/hour",
    },
}

# Réglages spécifiques au back-office administrateur (apps.administration) :
# cookies session/CSRF isolés, allowlist IP, TOTP... Importé en dernier pour
# pouvoir surcharger sans ambiguïté des réglages définis plus haut
# (SESSION_COOKIE_NAME, CSRF_COOKIE_NAME...).
from config.settings_admin import *  # noqa: E402,F401,F403
