# Generated by Django 4.2.30 on 2026-08-01 21:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('audits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_role', models.CharField(blank=True, default='', help_text="Rôle (snapshot) de l'acteur au moment de l'action.", max_length=32)),
                ('action', models.CharField(max_length=64)),
                ('target_type', models.CharField(blank=True, default='', max_length=64)),
                ('target_id', models.CharField(blank=True, default='', max_length=64)),
                ('reason', models.TextField(blank=True, default='')),
                ('before', models.JSONField(blank=True, null=True)),
                ('after', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=512)),
                ('request_id', models.CharField(blank=True, default='', max_length=64)),
                ('http_method', models.CharField(blank=True, default='', max_length=8)),
                ('path', models.CharField(blank=True, default='', max_length=255)),
                ('status_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('result', models.CharField(choices=[('success', 'Succès'), ('failure', 'Échec'), ('denied', 'Refusé')], default='success', max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(help_text="Membre du staff ayant déclenché l'action. PROTECT : on ne doit jamais pouvoir supprimer un utilisateur staff si cela effacerait la possibilité de retrouver les actions qu'il a menées.", on_delete=django.db.models.deletion.PROTECT, related_name='admin_action_logs', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(blank=True, help_text="Utilisateur final éventuellement ciblé par l'action (ex : suspension).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_action_logs_targeting_me', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Entrée d'audit administrateur",
                'verbose_name_plural': "Journal d'audit administrateur",
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='audits_admi_timesta_401bf4_idx'), models.Index(fields=['actor', '-timestamp'], name='audits_admi_actor_i_3fb263_idx'), models.Index(fields=['action', '-timestamp'], name='audits_admi_action_2a112c_idx'), models.Index(fields=['target_type', 'target_id'], name='audits_admi_target__88c59a_idx'), models.Index(fields=['target_user', '-timestamp'], name='audits_admi_target__113fff_idx'), models.Index(fields=['result', '-timestamp'], name='audits_admi_result_7bed63_idx')],
            },
        ),
    ]
