# Generated by Django 4.2.30 on 2026-05-02 22:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EpargnePersonnelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_projet', models.CharField(max_length=50)),
                ('objectif_cotisation', models.IntegerField()),
                ('montant_courant', models.DecimalField(decimal_places=0, max_digits=10)),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('hote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
