# Generated by Django 4.2.30 on 2026-05-27 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='epargnepersonnelle',
            name='categorie',
            field=models.CharField(blank=True, choices=[('VOYAGE', 'Voyage'), ('PROJET PERSONNEL', 'Projet personnel'), ('MARIAGE', 'Mariage'), ('EDUCATION', 'Education'), ('SANTÉ', 'Santé'), ('AUTRE', 'Autre')], max_length=50, null=True),
        ),
    ]
