# Generated by Django 4.2.30 on 2026-07-24 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solidarity', '0002_solidarity_versement_effectue'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='solidarity',
            constraint=models.CheckConstraint(check=models.Q(('objectif_cotisation__gt', 0)), name='solidarity_objectif_cotisation_positif'),
        ),
    ]
