# Generated by Django 4.2.30 on 2026-08-01 21:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('super_admin', 'Super administrateur'), ('operateur', 'Opérateur'), ('support', 'Support'), ('auditeur', 'Auditeur'), ('compliance', 'Conformité')], max_length=32, verbose_name='Rôle')),
                ('is_active', models.BooleanField(default=True, help_text="Un profil désactivé ne peut plus s'authentifier sur le back-office.", verbose_name='Actif')),
                ('totp_secret', models.CharField(blank=True, default='', max_length=64)),
                ('totp_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('last_totp_counter', models.BigIntegerField(blank=True, help_text="Dernier compteur TOTP (time-step) accepté, pour empêcher le rejeu d'un code.", null=True)),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('password_changed_at', models.DateTimeField(blank=True, null=True)),
                ('must_change_password', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_profiles_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Profil staff',
                'verbose_name_plural': 'Profils staff',
            },
        ),
        migrations.CreateModel(
            name='StaffLoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_tried', models.CharField(blank=True, default='', max_length=150)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=512)),
                ('stage', models.CharField(choices=[('password', 'Mot de passe'), ('totp', 'TOTP')], max_length=16)),
                ('success', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_login_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tentative de connexion staff',
                'verbose_name_plural': 'Tentatives de connexion staff',
                'indexes': [models.Index(fields=['ip_address', '-created_at'], name='administrat_ip_addr_066217_idx'), models.Index(fields=['user', '-created_at'], name='administrat_user_id_e5ed60_idx')],
            },
        ),
    ]
