# Generated by Django 4.2.30 on 2026-08-02 22:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='Clé')),
                ('value', models.JSONField(verbose_name='Valeur')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_settings_updated', to=settings.AUTH_USER_MODEL, verbose_name='Dernier auteur')),
            ],
            options={
                'verbose_name': 'Réglage plateforme',
                'verbose_name_plural': 'Réglages plateforme',
                'ordering': ['key'],
            },
        ),
    ]
