# Generated by Django 4.2.30 on 2026-05-02 22:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('savings', '0001_initial'),
        ('tontine', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solde_courant', models.DecimalField(decimal_places=0, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solde_courant', models.DecimalField(decimal_places=0, max_digits=10)),
                ('ref_transaction', models.CharField(max_length=25)),
                ('mode_de_paiement', models.CharField(choices=[('ORANGE', 'Orange'), ('MTN', 'Mtn'), ('WAVE', 'Wave'), ('MOOV', 'Moov'), ('SOLDE_COTICI', 'Solde Cotici')], max_length=20)),
                ('date_transaction', models.DateTimeField(auto_now_add=True)),
                ('montant_transaction', models.DecimalField(decimal_places=0, max_digits=10)),
                ('statut_transaction', models.CharField(choices=[('EN ATTENTE', 'En attente'), ('ANNULÉE', 'Annulée'), ('RÉUSSIE', 'Réussie'), ('ÉCHOUÉE', 'Échouée')], default='EN ATTENTE', max_length=20)),
                ('type_transaction', models.CharField(choices=[('RETRAIT', 'Retrait'), ('DÉPÔT', 'Dépôt'), ('VERSEMENT_EPARGNE_PERSONNELLE', 'Versement épargne personnelle'), ('DÉBIT', 'Débit')], max_length=35)),
                ('epargne', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='savings.epargnepersonnelle')),
                ('tontine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tontine.tontine')),
                ('tour', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tontine.tourtontine')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.wallet')),
            ],
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('epargne__isnull', False), ('tontine__isnull', True), ('tour__isnull', True), ('type_transaction', 'VERSEMENT_EPARGNE_PERSONNELLE')), models.Q(('epargne__isnull', True), ('tontine__isnull', True), ('tour__isnull', True), ('type_transaction', 'RETRAIT')), models.Q(('epargne__isnull', True), ('tontine__isnull', True), ('tour__isnull', True), ('type_transaction', 'DÉPÔT')), models.Q(('epargne__isnull', True), ('tontine__isnull', False), ('tour__isnull', False), ('type_transaction', 'DÉBIT')), _connector='OR'), name='wallet_transaction_fk_coherence_type'),
        ),
    ]
