# Generated by Django 4.2.30 on 2026-06-06 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_solidarity_transaction_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type_transaction',
            field=models.CharField(choices=[('RETRAIT', 'Retrait'), ('DÉPÔT', 'Dépôt'), ('VERSEMENT_EPARGNE_PERSONNELLE', 'Versement épargne personnelle'), ('RETRAIT_EPARGNE_PERSONNELLE', 'Retrait épargne personnelle'), ('DÉBIT', 'Débit'), ('CONTRIBUTION_SOLIDAIRE', 'Contribution solidaire'), ('VERSEMENT_SOLIDAIRE', 'Versement solidaire'), ('CONTRIBUTION_CAGNOTTE', 'Contribution cagnotte'), ('VERSEMENT_CAGNOTTE', 'Versement cagnotte')], max_length=35),
        ),
    ]
