# Generated by Django 4.2.30 on 2026-07-24 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0008_transaction_transaction_montant_transaction_positif_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='client_ref',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.UniqueConstraint(condition=models.Q(('client_ref__isnull', False)), fields=('wallet', 'client_ref'), name='unique_client_ref_par_wallet'),
        ),
    ]
