# Generated by Django 4.2.30 on 2026-05-02 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_display', models.CharField(blank=True, max_length=255)),
                ('action', models.CharField(choices=[('signup', 'Inscription'), ('login', 'Connexion'), ('logout', 'Déconnexion'), ('pin_changed', 'PIN modifié'), ('profile_updated', 'Profil mis à jour'), ('wallet_created', 'Portefeuille créé'), ('deposit_initiated', 'Dépôt initié'), ('deposit_confirmed', 'Dépôt confirmé'), ('withdrawal_initiated', 'Retrait initié'), ('withdrawal_confirmed', 'Retrait confirmé'), ('withdrawal_rejected', 'Retrait rejeté'), ('transfer_initiated', 'Transfert initié'), ('transfer_completed', 'Transfert effectué'), ('transfer_failed', 'Transfert échoué'), ('transaction_created', 'Transaction créée'), ('transaction_succeeded', 'Transaction réussie'), ('transaction_failed', 'Transaction échouée'), ('transaction_cancelled', 'Transaction annulée'), ('savings_goal_created', "Objectif d'épargne créé"), ('savings_goal_updated', "Objectif d'épargne mis à jour"), ('savings_goal_deleted', "Objectif d'épargne supprimé"), ('savings_contribution_added', 'Versement épargne ajouté'), ('savings_withdrawal_requested', 'Retrait épargne demandé'), ('savings_withdrawal_approved', 'Retrait épargne approuvé'), ('savings_withdrawal_rejected', 'Retrait épargne rejeté'), ('savings_goal_reached', "Objectif d'épargne atteint"), ('tontine_created', 'Tontine créée'), ('tontine_updated', 'Tontine mise à jour'), ('tontine_closed', 'Tontine clôturée'), ('member_invited', 'Membre invité'), ('member_joined', 'Membre rejoint'), ('member_left', 'Membre parti'), ('member_removed', 'Membre retiré'), ('rule_updated', 'Règles de tontine mises à jour'), ('contribution_recorded', 'Cotisation enregistrée'), ('penalty_assigned', 'Pénalité attribuée'), ('penalty_paid', 'Pénalité réglée'), ('round_started', 'Tour démarré'), ('round_closed', 'Tour clôturé'), ('payout_executed', 'Décaissement effectué'), ('solidarity_group_created', 'Groupe solidaire créé'), ('aid_request_created', "Demande d'aide créée"), ('aid_request_validated', "Demande d'aide validée"), ('aid_request_rejected', "Demande d'aide rejetée"), ('aid_disbursement_executed', 'Aide décaissée'), ('invitation_link_generated', "Lien d'invitation généré"), ('invitation_sent', 'Invitation envoyée'), ('invitation_accepted', 'Invitation acceptée'), ('invitation_declined', 'Invitation refusée'), ('invitation_expired', 'Invitation expirée'), ('invitation_revoked', 'Invitation révoquée'), ('offboarding_requested', 'Sortie demandée'), ('offboarding_started', 'Sortie engagée'), ('offboarding_approved', 'Sortie approuvée'), ('offboarding_rejected', 'Sortie refusée'), ('offboarding_cancelled', 'Sortie annulée'), ('account_purged', 'Compte effacé')], max_length=64)),
                ('resource', models.CharField(blank=True, default='-', max_length=255)),
                ('status', models.CharField(choices=[('success', 'Succès'), ('failure', 'Échec')], default='success', max_length=10)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "Entrée d'audit",
                'verbose_name_plural': "Journal d'audit",
                'ordering': ['-timestamp'],
            },
        ),
    ]
