# Generated by Django 4.2.30 on 2026-05-27 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0002_epargnepersonnelle_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='epargnepersonnelle',
            name='duree',
            field=models.IntegerField(default=0),
        ),
    ]
