# Generated by Django 4.2.30 on 2026-06-01 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0003_epargnepersonnelle_duree'),
    ]

    operations = [
        migrations.AddField(
            model_name='epargnepersonnelle',
            name='date_archivage',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='epargnepersonnelle',
            name='date_suppression',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='epargnepersonnelle',
            name='etat',
            field=models.CharField(choices=[('ACTIF', 'Actif'), ('ARCHIVÉ', 'Archivé'), ('SUPPRIMÉ', 'Supprimé')], default='ACTIF', max_length=20),
        ),
    ]
