# Generated by Django 4.2.30 on 2026-07-24 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0005_epargnepersonnelle_objectif_atteint'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='epargnepersonnelle',
            constraint=models.CheckConstraint(check=models.Q(('montant_courant__gte', 0)), name='epargnepersonnelle_montant_courant_non_negatif'),
        ),
    ]
