# Generated by Django 4.2.30 on 2026-08-02 22:57

import apps.kyc.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KycSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dossier_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text="Identifiant non séquentiel, utilisé dans le chemin de stockage des pièces pour qu'aucune URL ne soit devinable par incrémentation.", unique=True, verbose_name='Identifiant du dossier')),
                ('niveau_demande', models.CharField(choices=[('NIVEAU_1', 'Niveau 1 — identité déclarée'), ('NIVEAU_2', 'Niveau 2 — pièce officielle vérifiée'), ('NIVEAU_3', 'Niveau 3 — vérification renforcée')], default='NIVEAU_2', max_length=16, verbose_name='Niveau demandé')),
                ('type_piece', models.CharField(choices=[('CNI', "Carte nationale d'identité"), ('PASSEPORT', 'Passeport'), ('PERMIS', 'Permis de conduire'), ('ATTESTATION', "Attestation d'identité")], max_length=16, verbose_name='Type de pièce')),
                ('numero_piece', models.CharField(max_length=64, verbose_name='Numéro de pièce')),
                ('date_expiration_piece', models.DateField(blank=True, null=True, verbose_name='Expiration de la pièce')),
                ('nom_declare', models.CharField(blank=True, default='', max_length=150)),
                ('prenoms_declares', models.CharField(blank=True, default='', max_length=150)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('document_recto', models.FileField(upload_to=apps.kyc.models.kyc_document_path, verbose_name='Pièce — recto')),
                ('document_verso', models.FileField(blank=True, upload_to=apps.kyc.models.kyc_document_path, verbose_name='Pièce — verso')),
                ('selfie', models.FileField(blank=True, upload_to=apps.kyc.models.kyc_document_path, verbose_name='Photo du porteur')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', "En attente d'examen"), ('EN_EXAMEN', "En cours d'examen"), ('APPROUVE', 'Approuvé'), ('REJETE', 'Rejeté')], default='EN_ATTENTE', max_length=16, verbose_name='Statut')),
                ('motif_decision', models.TextField(blank=True, default='', help_text="Obligatoire pour un rejet ; conservé pour l'opposabilité.", verbose_name='Motif de la décision')),
                ('niveau_accorde', models.CharField(blank=True, choices=[('NIVEAU_1', 'Niveau 1 — identité déclarée'), ('NIVEAU_2', 'Niveau 2 — pièce officielle vérifiée'), ('NIVEAU_3', 'Niveau 3 — vérification renforcée')], default='', help_text="Peut être inférieur au niveau demandé : un dossier incomplet peut justifier d'accorder un palier plus bas plutôt que de tout rejeter.", max_length=16, verbose_name='Niveau accordé')),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('date_decision', models.DateTimeField(blank=True, null=True)),
                ('decide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dossiers_kyc_decides', to=settings.AUTH_USER_MODEL, verbose_name='Décidé par')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dossiers_kyc', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Dossier KYC',
                'verbose_name_plural': 'Dossiers KYC',
                'ordering': ['date_soumission'],
                'indexes': [models.Index(fields=['statut', 'date_soumission'], name='kyc_kycsubm_statut_250076_idx'), models.Index(fields=['user', '-date_soumission'], name='kyc_kycsubm_user_id_7b1314_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='kycsubmission',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('statut__in', ['APPROUVE', 'REJETE']), _negated=True), models.Q(('date_decision__isnull', False), ('decide_par__isnull', False)), _connector='OR'), name='kyc_decision_horodatee_et_imputable'),
        ),
        migrations.AddConstraint(
            model_name='kycsubmission',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('statut', 'REJETE'), _negated=True), models.Q(('motif_decision', ''), _negated=True), _connector='OR'), name='kyc_rejet_motive'),
        ),
        migrations.AddConstraint(
            model_name='kycsubmission',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('statut', 'APPROUVE'), _negated=True), models.Q(('niveau_accorde', ''), _negated=True), _connector='OR'), name='kyc_approbation_precise_le_niveau'),
        ),
    ]
