from django.urls import path

from .views import (
    accept_invitation,
    attribute_penalite,
    changer_tour,
    cotiser_tontine,
    create_tontine,
    list_chat_messages,
    post_chat_message,
    define_tontine_regle,
    demarrer_tontine,
    get_tontine_detail,
    health,
    list_my_invitations,
    list_my_tontines_recruiting,
    list_tontines,
    preview_invitation,
    refuse_invitation,
    send_invitation,
    set_ordre_ramassage,
)

urlpatterns = [
    path("health/", health, name="tontine-health"),
    path("", list_tontines, name="tontine-list"),
    path("recruiting/", list_my_tontines_recruiting, name="tontine-list-recruiting"),
    path("detail/", get_tontine_detail, name="tontine-detail"),
    path("create/", create_tontine, name="tontine-create"),
    path("regles/", define_tontine_regle, name="tontine-define-regles"),
    path("invitations/", send_invitation, name="tontine-send-invitation"),
    path("invitations/mine/", list_my_invitations, name="tontine-my-invitations"),
    path("invitations/preview/", preview_invitation, name="tontine-preview-invitation"),
    path("invitations/accept/", accept_invitation, name="tontine-accept-invitation"),
    path("invitations/refuse/", refuse_invitation, name="tontine-refuse-invitation"),
    path("ordre/", set_ordre_ramassage, name="tontine-set-ordre"),
    path("cotiser/", cotiser_tontine, name="tontine-cotiser"),
    path("tours/demarrer/", demarrer_tontine, name="tontine-demarrer"),
    path("penalites/attribuer/", attribute_penalite, name="tontine-attribute-penalite"),
    path("tours/changer/", changer_tour, name="tontine-changer-tour"),
    path("chat/", list_chat_messages, name="tontine-chat-list"),
    path("chat/send/", post_chat_message, name="tontine-chat-send"),
]
