# Generated by Django 4.2.30 on 2026-06-06 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tontine', '0009_remove_tontine_beneficiaire_telephone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cagnotte',
            fields=[
                ('tontine_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tontine.tontine')),
                ('nom_cagnotte', models.CharField(max_length=15)),
                ('objectif_cotisation', models.IntegerField(help_text='Montant cible de la collecte en FCFA.')),
                ('objectif_atteint', models.BooleanField(default=False)),
                ('description_projet', models.CharField(max_length=255)),
                ('recuperation_effectue', models.BooleanField(default=False, help_text="Récupération de la collecte par l'organisateur.")),
            ],
            options={
                'verbose_name': 'Cagnotte',
                'verbose_name_plural': 'Cagnotte',
            },
            bases=('tontine.tontine',),
        ),
    ]
