# Generated by Django 4.2.30 on 2026-06-06 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cagnotte', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cagnotte',
            name='description_projet',
        ),
    ]
