# Generated by Django 4.2.30 on 2026-07-11 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cagnotte', '0002_remove_cagnotte_description_projet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cagnotte',
            old_name='nom_cagnotte',
            new_name='numero_cagnotte',
        ),
    ]
