# Generated by Django 4.2.30 on 2026-05-18 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tontine', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tontineregle',
            name='ordre_aleatoire',
        ),
        migrations.AddField(
            model_name='tontineregle',
            name='ordre_ramassage',
            field=models.CharField(choices=[("DÉFINI PAR L'ADMIN", "Défini par l'admin"), ('ALÉATOIRE', 'Aléatoire')], default='ALÉATOIRE', max_length=25),
        ),
    ]
