# Generated by Django 4.2.30 on 2026-05-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tontine', '0002_remove_tontineregle_ordre_aleatoire_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tontineregle',
            name='nombre_tours',
            field=models.IntegerField(default=1),
        ),
    ]
