# Generated by Django 4.2.30 on 2026-05-18 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tontine', '0003_tontineregle_nombre_tours'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourtontine',
            name='statut_tour',
            field=models.CharField(choices=[('EN COURS', 'En cours'), ('TERMINÉ', 'Terminé'), ('REPORTÉ', 'Reporté')], default='EN COURS', max_length=25),
        ),
        migrations.AlterField(
            model_name='tontineregle',
            name='nombre_tours',
            field=models.IntegerField(),
        ),
    ]
