# Generated by Django 4.2.30 on 2026-06-01 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tontine', '0005_tontineregle_montant_cotisation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tontineregle',
            name='objectif_cotisation',
            field=models.DecimalField(decimal_places=0, help_text='Montant total à atteindre pour le groupe.', max_digits=10),
        ),
    ]
