# Generated by Django 4.2.30 on 2026-06-05 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tontine', '0008_tontine_beneficiaire_telephone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tontine',
            name='beneficiaire_telephone',
        ),
        migrations.AlterField(
            model_name='tontineregle',
            name='objectif_cotisation',
            field=models.DecimalField(decimal_places=0, help_text='Volume total sur le cycle (dérivé pour les tontines de groupe).', max_digits=10),
        ),
    ]
