# Generated by Django 4.2.30 on 2026-07-24 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tontine', '0010_tontine_etat'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='tontineregle',
            constraint=models.CheckConstraint(check=models.Q(('montant_cotisation__gt', 0)), name='tontineregle_montant_cotisation_positif'),
        ),
        migrations.AddConstraint(
            model_name='tontineregle',
            constraint=models.CheckConstraint(check=models.Q(('objectif_cotisation__gt', 0)), name='tontineregle_objectif_cotisation_positif'),
        ),
        migrations.AddConstraint(
            model_name='tontineregle',
            constraint=models.CheckConstraint(check=models.Q(('montant_penalite__gte', 0)), name='tontineregle_montant_penalite_non_negatif'),
        ),
        migrations.AddConstraint(
            model_name='tourtontine',
            constraint=models.CheckConstraint(check=models.Q(('montant_depose__gte', 0)), name='tourtontine_montant_depose_non_negatif'),
        ),
    ]
