# Generated by Django 4.2.30 on 2026-08-01 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tontine', '0011_tontineregle_tontineregle_montant_cotisation_positif_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='penalite',
            name='date_annulation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='penalite',
            name='est_annulee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='penalite',
            name='motif',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='tourtontine',
            name='date_echeance',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='tourtontine',
            index=models.Index(fields=['statut_tour', 'date_echeance'], name='tontine_tou_statut__1ee7af_idx'),
        ),
    ]
