# Generated by Django 4.2.30 on 2026-08-02 20:04
# Splitted manually from the auto-generated migration: cette migration ne
# contient QUE les AddField, séparés des AddConstraint/AddIndex (0016) pour
# que l'échec de validation d'une contrainte (données existantes incohérentes)
# soit diagnosticable et rejouable indépendamment de l'ajout des colonnes.
# Voir 0015 pour le backfill de données (`delai_grace_heures`).

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tontine', '0013_backfill_tour_date_echeance'),
    ]

    operations = [
        migrations.AddField(
            model_name='penalite',
            name='date_derniere_tentative',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='penalite',
            name='est_automatique',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='penalite',
            name='nombre_tentatives',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='penalite',
            name='ref_transaction_reglement',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='penalite',
            name='tour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='penalites', to='tontine.tourtontine'),
        ),
        migrations.AddField(
            model_name='tontineregle',
            name='delai_grace_heures',
            field=models.PositiveIntegerField(default=24, help_text="Heures après l'échéance du tour avant constat d'une pénalité (0 = immédiat)."),
        ),
        migrations.AddField(
            model_name='tontineregle',
            name='penalites_automatiques',
            field=models.BooleanField(default=False),
        ),
    ]
