# Generated by Django 4.2.30 on 2026-08-02 20:04
# Splitted manually from the auto-generated migration : cette migration ne
# contient que les AddIndex/AddConstraint (séparés des AddField de 0014 et du
# backfill de données de 0015), pour rester rejouable isolément en cas
# d'échec de validation (données existantes incohérentes avec une contrainte).

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tontine', '0015_backfill_delai_grace'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='penalite',
            index=models.Index(condition=models.Q(('est_annulee', False), ('est_reglee', False)), fields=['user', 'date_attribution_penalite'], name='idx_penalite_impayee_par_user'),
        ),
        migrations.AddIndex(
            model_name='penalite',
            index=models.Index(condition=models.Q(('est_annulee', False), ('est_reglee', False)), fields=['tontine', 'user'], name='idx_penalite_impayee_tontine'),
        ),
        migrations.AddConstraint(
            model_name='penalite',
            constraint=models.CheckConstraint(check=models.Q(('est_reglee', True), ('est_annulee', True), _negated=True), name='penalite_reglee_xor_annulee'),
        ),
        migrations.AddConstraint(
            model_name='penalite',
            constraint=models.CheckConstraint(check=models.Q(('montant_penalite__gte', 0), ('montant_due__gte', 0)), name='penalite_montants_non_negatifs'),
        ),
        migrations.AddConstraint(
            model_name='penalite',
            constraint=models.CheckConstraint(check=models.Q(('est_automatique', False), ('tour__isnull', False), _connector='OR'), name='penalite_auto_exige_tour'),
        ),
        migrations.AddConstraint(
            model_name='penalite',
            constraint=models.UniqueConstraint(condition=models.Q(('est_automatique', True)), fields=('tour', 'user'), name='uniq_penalite_auto_par_tour_et_user'),
        ),
        migrations.AddConstraint(
            model_name='tontineregle',
            constraint=models.CheckConstraint(check=models.Q(('delai_grace_heures__lte', 720)), name='tontineregle_delai_grace_max_720h'),
        ),
        migrations.AddConstraint(
            model_name='tontineregle',
            constraint=models.CheckConstraint(check=models.Q(('penalites_automatiques', False), ('montant_penalite__gt', 0), _connector='OR'), name='tontineregle_penalites_auto_exigent_montant'),
        ),
    ]
