# Generated by Django 4.2.30 on 2026-08-03 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tontine', '0016_penalite_constraints'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetteCotisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_initial', models.DecimalField(decimal_places=0, help_text='Montant de la cotisation manquée au moment du constat (= montant_cotisation de la règle à cette date).', max_digits=10)),
                ('montant_du', models.DecimalField(decimal_places=0, help_text='Solde restant dû. Le règlement est tout-ou-rien (jamais fractionnaire) : passe directement à 0.', max_digits=10)),
                ('est_reglee', models.BooleanField(default=False)),
                ('date_reglement', models.DateTimeField(blank=True, null=True)),
                ('est_annulee', models.BooleanField(default=False)),
                ('date_annulation', models.DateTimeField(blank=True, null=True)),
                ('ref_transaction_reglement', models.CharField(blank=True, default='', max_length=25)),
                ('motif', models.CharField(blank=True, default='', max_length=255)),
                ('date_constat', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='tourtontine',
            name='montant_attendu',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Montant théorique attendu pour ce tour (montant_cotisation × nombre_max de la règle), snapshotté à la clôture — permet de calculer le taux de collecte du pot partiel sans dépendre de la règle courante, qui peut évoluer après coup.', max_digits=10),
        ),
        migrations.AddField(
            model_name='tourtontine',
            name='montant_compense_beneficiaire',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Montant retenu sur le pot AVANT versement au bénéficiaire, au titre de sa propre dette (cotisation manquée à son propre tour + pénalité éventuelle) — voir règle métier de compensation du bénéficiaire. Toujours 0 si le bénéficiaire a lui-même cotisé.', max_digits=10),
        ),
        migrations.AddField(
            model_name='tourtontine',
            name='montant_verse_beneficiaire',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Montant NET effectivement crédité au wallet du bénéficiaire (= montant_depose − montant_compense_beneficiaire, plancher à 0F : jamais de versement négatif). Pour un tour clôturé normalement (TERMINÉ), égal à montant_depose.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='tourtontine',
            name='statut_tour',
            field=models.CharField(choices=[('EN COURS', 'En cours'), ('TERMINÉ', 'Terminé'), ('REPORTÉ', 'Reporté'), ('CLÔTURÉ AVEC IMPAYÉS', 'Clôturé avec impayés')], default='EN COURS', max_length=25),
        ),
        migrations.AddConstraint(
            model_name='tourtontine',
            constraint=models.CheckConstraint(check=models.Q(('montant_attendu__gte', 0)), name='tourtontine_montant_attendu_non_negatif'),
        ),
        migrations.AddConstraint(
            model_name='tourtontine',
            constraint=models.CheckConstraint(check=models.Q(('montant_compense_beneficiaire__gte', 0)), name='tourtontine_montant_compense_non_negatif'),
        ),
        migrations.AddConstraint(
            model_name='tourtontine',
            constraint=models.CheckConstraint(check=models.Q(('montant_verse_beneficiaire__gte', 0)), name='tourtontine_montant_verse_beneficiaire_non_negatif'),
        ),
        migrations.AddField(
            model_name='dettecotisation',
            name='beneficiaire_lese',
            field=models.ForeignKey(help_text='Bénéficiaire du tour manqué au moment du constat : créancier figé de cette dette.', on_delete=django.db.models.deletion.PROTECT, related_name='dettes_cotisation_a_recevoir', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dettecotisation',
            name='debiteur',
            field=models.ForeignKey(help_text="Membre qui n'a pas cotisé à `tour`.", on_delete=django.db.models.deletion.CASCADE, related_name='dettes_cotisation_dues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dettecotisation',
            name='tontine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dettes_cotisation', to='tontine.tontine'),
        ),
        migrations.AddField(
            model_name='dettecotisation',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dettes_cotisation', to='tontine.tourtontine'),
        ),
        migrations.AddIndex(
            model_name='dettecotisation',
            index=models.Index(condition=models.Q(('est_annulee', False), ('est_reglee', False)), fields=['debiteur', 'date_constat'], name='idx_dette_impayee_par_debiteur'),
        ),
        migrations.AddIndex(
            model_name='dettecotisation',
            index=models.Index(condition=models.Q(('est_annulee', False), ('est_reglee', False)), fields=['beneficiaire_lese', 'date_constat'], name='idx_dette_impayee_par_benef'),
        ),
        migrations.AddConstraint(
            model_name='dettecotisation',
            constraint=models.CheckConstraint(check=models.Q(('montant_initial__gt', 0)), name='dette_montant_initial_positif'),
        ),
        migrations.AddConstraint(
            model_name='dettecotisation',
            constraint=models.CheckConstraint(check=models.Q(('montant_du__gte', 0)), name='dette_montant_du_non_negatif'),
        ),
        migrations.AddConstraint(
            model_name='dettecotisation',
            constraint=models.UniqueConstraint(fields=('tour', 'debiteur'), name='uniq_dette_cotisation_par_tour_et_debiteur'),
        ),
        migrations.AddConstraint(
            model_name='dettecotisation',
            constraint=models.CheckConstraint(check=models.Q(('est_reglee', True), ('est_annulee', True), _negated=True), name='dette_reglee_xor_annulee'),
        ),
        migrations.AddConstraint(
            model_name='dettecotisation',
            constraint=models.CheckConstraint(check=models.Q(('est_reglee', True), ('montant_du__gt', 0), _negated=True), name='dette_reglee_exige_montant_du_nul'),
        ),
    ]
